#!/usr/bin/env python3
"""Generate CharacterLabKnownOptions.cs from _analysis.json.

Run generate_appendices.py first — it writes _analysis.json from base-game data only.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ANALYSIS = ROOT / "_analysis.json"
OUTPUT = ROOT.parents[1] / "LokrCharacterLab" / "Editor" / "CharacterLabKnownOptions.cs"

KEYS = [
    ("AttackTypes", "attack_types"),
    ("StatNames", "stat_names"),
    ("StateFlags", "state_names"),
    ("ModelValues", "model_values"),
    ("SoundAssetIds", "sound_asset_ids"),
    ("SoundEvents", "sound_events"),
    ("CinematicTags", "cinematic_tags"),
    ("SkillIds", "skill_ids"),
]


def names_only(entries: list) -> list[str]:
    return [entry[0] for entry in entries if entry and entry[0]]


def csharp_string_array(name: str, values: list[str]) -> str:
    lines = [f"\t\tpublic static readonly string[] {name} = new string[]"]
    lines.append("\t\t{")
    for value in values:
        escaped = value.replace("\\", "\\\\").replace("\"", "\\\"")
        lines.append(f"\t\t\t\"{escaped}\",")
    lines.append("\t\t};")
    return "\n".join(lines)


def main() -> None:
    if not ANALYSIS.exists():
        raise SystemExit(
            f"Missing {ANALYSIS}. Run generate_appendices.py first."
        )
    data = json.loads(ANALYSIS.read_text(encoding="utf-8"))
    blocks = [csharp_string_array(csharp_name, names_only(data.get(json_key, []))) for csharp_name, json_key in KEYS]

    body = "\n\n".join(blocks)
    source = f"""// Auto-generated by docs/character-reference/generate_character_lab_known_options.py — do not edit by hand.
// Source: _analysis.json from generate_appendices.py (base-game enumerations only).

namespace LokrCharacterLab.Editor
{{
\t/// <summary>Built-in Character Lab combobox defaults from vanilla/base-game data. Extended at runtime via CharacterLabOptionsAPI.</summary>
\tinternal static class CharacterLabKnownOptions
\t{{
{body}
\t}}
}}
"""
    OUTPUT.write_text(source, encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
