#!/usr/bin/env python3
"""Scan decompiled Ironhide.Legends C# sources and list every namespace.

Usage (from repo root):
    python3 bepinex/docs/list_base_game_namespaces.py
    python3 bepinex/docs/list_base_game_namespaces.py --check

Writes bepinex/docs/base-game-namespaces.md by default.
"""

from __future__ import annotations

import argparse
import os
import re
from collections import Counter
from datetime import date

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_ROOT = os.path.expanduser(
    "~/dev/lokr-modding/lokr-modding/ih-original/Ironhide.Legends"
)
DEFAULT_OUT = os.path.join(SCRIPT_DIR, "base-game-namespaces.md")

NAMESPACE_RE = re.compile(r"^\s*namespace\s+([\w.]+)\s*(?:[{;]|$)", re.MULTILINE)
GLOBAL_LABEL = "(global)"


def display_path(path: str) -> str:
    home = os.path.expanduser("~")
    if path.startswith(home):
        return "~" + path[len(home) :]
    return path


def scan_namespaces(root: str) -> tuple[Counter[str], list[str]]:
    """Return per-namespace file counts and paths of files with no namespace."""
    counts: Counter[str] = Counter()
    no_namespace: list[str] = []

    for dirpath, _, filenames in os.walk(root):
        for filename in filenames:
            if not filename.endswith(".cs"):
                continue
            path = os.path.join(dirpath, filename)
            try:
                with open(path, encoding="utf-8", errors="replace") as f:
                    text = f.read()
            except OSError as err:
                raise SystemExit(f"Failed to read {path}: {err}") from err

            match = NAMESPACE_RE.search(text)
            if match:
                counts[match.group(1)] += 1
            else:
                counts[GLOBAL_LABEL] += 1
                no_namespace.append(os.path.relpath(path, root))

    return counts, no_namespace


def top_level_roots(counts: Counter[str]) -> Counter[str]:
    roots: Counter[str] = Counter()
    for ns, count in counts.items():
        if ns == GLOBAL_LABEL:
            roots[GLOBAL_LABEL] = count
        else:
            roots[ns.split(".", 1)[0]] += count
    return roots


def namespace_tree(counts: Counter[str]) -> dict:
    """Nested dict tree keyed by namespace segment (excludes global)."""
    named = sorted(k for k in counts if k != GLOBAL_LABEL)
    has_children: set[str] = set()
    for ns in named:
        parts = ns.split(".")
        for i in range(1, len(parts)):
            has_children.add(".".join(parts[:i]))

    tree: dict = {}
    for ns in named:
        parts = ns.split(".")
        node = tree
        if ns in has_children:
            for part in parts:
                node = node.setdefault(part, {})
        else:
            for part in parts[:-1]:
                node = node.setdefault(part, {})
        node.setdefault("_namespaces", []).append((ns, counts[ns]))
    return tree


def render_tree(node: dict, indent: int = 0) -> list[str]:
    lines: list[str] = []
    prefix = "  " * indent

    for key in sorted(k for k in node if k != "_namespaces"):
        child = node[key]
        child_total = sum(c for _, c in child.get("_namespaces", []))
        child_total += sum_tree(child)
        lines.append(f"{prefix}- **{key}** ({child_total} files)")
        for ns, count in sorted(child.get("_namespaces", [])):
            lines.append(f"{prefix}  - `{ns}` ({count} files)")
        lines.extend(render_tree(child, indent + 1))

    for ns, count in sorted(node.get("_namespaces", [])):
        if indent == 0:
            lines.append(f"{prefix}- `{ns}` ({count} files)")

    return lines


def sum_tree(node: dict) -> int:
    total = 0
    for key, child in node.items():
        if key == "_namespaces":
            continue
        total += sum(c for _, c in child.get("_namespaces", []))
        total += sum_tree(child)
    return total


def write_markdown(
    *,
    root: str,
    out_path: str,
    counts: Counter[str],
    no_namespace: list[str],
) -> None:
    total_files = sum(counts.values())
    named = {k: v for k, v in counts.items() if k != GLOBAL_LABEL}
    unique_named = len(named)
    roots = top_level_roots(counts)
    today = date.today().isoformat()

    lines = [
        "# Base game namespaces",
        "",
        "Every C# namespace declared in the decompiled Legends of Kingdom Rush source",
        "(`Ironhide.Legends`). Generated by",
        "[`list_base_game_namespaces.py`](list_base_game_namespaces.py).",
        "",
        f"**Source tree:** `{display_path(root)}`  ",
        f"**Generated:** {today}",
        "",
        "## Summary",
        "",
        f"| Metric | Count |",
        f"|--------|------:|",
        f"| `.cs` files scanned | {total_files} |",
        f"| Distinct declared namespaces | {unique_named} |",
        f"| Files in `(global)` (no `namespace` line) | {counts.get(GLOBAL_LABEL, 0)} |",
        f"| Top-level namespace roots | {len(roots)} |",
        "",
        "Most files live under `Ironhide.*` — the first-party game code. The `(global)",
        "bucket is mostly decompiler output at the tree root (extension methods, UI glue,",
        "third-party snippets) where no explicit namespace was recovered.",
        "",
        "## Top-level roots",
        "",
        "File counts grouped by the first segment of each declared namespace (plus",
        "`(global)`).",
        "",
        "| Root | Files |",
        "|------|------:|",
    ]

    for root_name, count in roots.most_common():
        lines.append(f"| `{root_name}` | {count} |")

    lines.extend([
        "",
        "## Namespace tree",
        "",
        "Hierarchical view. Leaf entries are fully qualified namespace names with file",
        "counts. Intermediate nodes show how many files sit under that prefix.",
        "",
    ])
    lines.extend(render_tree(namespace_tree(counts)))

    lines.extend([
        "",
        "## Full list (alphabetical)",
        "",
        "| Namespace | Files |",
        "|-----------|------:|",
    ])

    for ns, count in sorted(counts.items(), key=lambda item: item[0].lower()):
        if ns == GLOBAL_LABEL:
            lines.append(f"| `(global)` | {count} |")
        else:
            lines.append(f"| `{ns}` | {count} |")

    lines.extend([
        "",
        "## `(global)` sample paths",
        "",
        "First 40 root-relative paths for files with no `namespace` declaration",
        f"({len(no_namespace)} total). These are not a separate namespace — they compile",
        "into the global namespace.",
        "",
    ])
    for rel in sorted(no_namespace)[:40]:
        lines.append(f"- `{rel}`")
    if len(no_namespace) > 40:
        lines.append(f"- … and {len(no_namespace) - 40} more")

    lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        default=DEFAULT_ROOT,
        help=f"Path to Ironhide.Legends sources (default: {DEFAULT_ROOT})",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUT,
        help=f"Markdown output path (default: {DEFAULT_OUT})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if output markdown would change (for CI)",
    )
    args = parser.parse_args()

    root = os.path.expanduser(args.root)
    if not os.path.isdir(root):
        raise SystemExit(f"Source tree not found: {root}")

    counts, no_namespace = scan_namespaces(root)

    if args.check:
        import tempfile

        with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False) as tmp:
            tmp_path = tmp.name
        write_markdown(
            root=root,
            out_path=tmp_path,
            counts=counts,
            no_namespace=no_namespace,
        )
        existing = ""
        if os.path.isfile(args.output):
            with open(args.output, encoding="utf-8") as f:
                existing = f.read()
        with open(tmp_path, encoding="utf-8") as f:
            generated = f.read()
        os.unlink(tmp_path)
        if generated != existing:
            raise SystemExit(f"{args.output} is out of date — re-run without --check")
        print(f"OK: {args.output} is up to date ({sum(counts.values())} files)")
        return 0

    write_markdown(
        root=root,
        out_path=args.output,
        counts=counts,
        no_namespace=no_namespace,
    )
    print(f"Wrote {args.output}")
    print(
        f"  {sum(counts.values())} files, "
        f"{len(counts) - (1 if GLOBAL_LABEL in counts else 0)} declared namespaces, "
        f"{counts.get(GLOBAL_LABEL, 0)} global"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
